In [1]:
import numpy as np
import qutip

In [114]:
g = 0.8
N_meas = 10000
sup = np.exp(-g**2/2)
M_qubit = np.array([[1, sup],[sup, 1]])
QM_qubit = qutip.Qobj(M_qubit)

In [115]:
QM_qubit

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[1.         0.72614904]
 [0.72614904 1.        ]]

In [116]:
M = qutip.tensor(QM_qubit for _ in range(2))
M

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[1.         0.72614904 0.72614904 0.52729242]
 [0.72614904 1.         0.52729242 0.72614904]
 [0.72614904 0.52729242 1.         0.72614904]
 [0.52729242 0.72614904 0.72614904 1.        ]]

In [117]:
rho = qutip.rand_dm(2*[2])
rho

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.28214825+0.j          0.0239924 -0.03671457j -0.00370335-0.02285874j
  -0.08800221-0.14017756j]
 [ 0.0239924 +0.03671457j  0.03302357+0.j          0.05604219+0.00352245j
  -0.00567785-0.03947318j]
 [-0.00370335+0.02285874j  0.05604219-0.00352245j  0.34231667+0.j
   0.05746103-0.22538231j]
 [-0.08800221+0.14017756j -0.00567785+0.03947318j  0.05746103+0.22538231j
   0.34251151+0.j        ]]

In [118]:
qutip.Qobj(np.multiply(M.full(), rho.full()), dims = rho.dims)

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.28214825+0.j          0.01742206-0.02666025j -0.00268918-0.01659885j
  -0.0464029 -0.07391456j]
 [ 0.01742206+0.02666025j  0.03302357+0.j          0.02955062+0.00185736j
  -0.00412296-0.02866341j]
 [-0.00268918+0.01659885j  0.02955062-0.00185736j  0.34231667+0.j
   0.04172527-0.16366115j]
 [-0.0464029 +0.07391456j -0.00412296+0.02866341j  0.04172527+0.16366115j
   0.34251151+0.j        ]]

In [119]:
g2 = g**2
std = np.sqrt((g2 +1)/(g2*N_meas))
noise = np.random.normal(0,std)
print(std,noise)

0.016007810593582122 0.02198101274541291


In [12]:
Had_qubit = qutip.gates.snot()
Had_qubit

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

In [26]:
Had = qutip.tensor(Had_qubit for _ in range(2))
Had

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]

In [38]:
S_qubit = qutip.gates.phasegate(np.pi/2)
S = qutip.tensor(S_qubit for _ in range(2))
S.dag()

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=False
Qobj data =
[[ 1.000000e+00-0.0000000e+00j  0.000000e+00+0.0000000e+00j
   0.000000e+00+0.0000000e+00j  0.000000e+00+0.0000000e+00j]
 [ 0.000000e+00+0.0000000e+00j  6.123234e-17-1.0000000e+00j
   0.000000e+00+0.0000000e+00j  0.000000e+00+0.0000000e+00j]
 [ 0.000000e+00+0.0000000e+00j  0.000000e+00+0.0000000e+00j
   6.123234e-17-1.0000000e+00j  0.000000e+00+0.0000000e+00j]
 [ 0.000000e+00+0.0000000e+00j  0.000000e+00+0.0000000e+00j
   0.000000e+00+0.0000000e+00j -1.000000e+00-1.2246468e-16j]]

In [30]:
Had*S

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=False
Qobj data =
[[ 0.5+0.j   0. +0.5j  0. +0.5j -0.5+0.j ]
 [ 0.5+0.j   0. -0.5j  0. +0.5j  0.5+0.j ]
 [ 0.5+0.j   0. +0.5j  0. -0.5j  0.5+0.j ]
 [ 0.5+0.j   0. -0.5j  0. -0.5j -0.5+0.j ]]